FROM postgres:latest

RUN mkdir -p /storely_postgres_ssl
COPY ./tls/server.key /storely_postgres_ssl
COPY ./tls/server.crt /storely_postgres_ssl
COPY ./config/pg_hba.conf /storely_postgres_ssl
RUN chown postgres:postgres /storely_postgres_ssl/server.key
RUN chmod 600 /storely_postgres_ssl/server.key
